import { EventItem } from './event';

export const mockEvents: EventItem[] = [
  {
    id: 1,
    type: 'sport',
    name: 'Футбольный матч',
    description: 'Местный турнир по футболу',
    location: 'Стадион “Спартак”',
    participants: 22,
  },
  {
    id: 2,
    type: 'music',
    name: 'Jazz Night',
    description: 'Вечер джазовой музыки',
    location: 'Клуб “Blue Note”',
    genre: 'Jazz',
  },
  {
    id: 3,
    type: 'sport',
    name: 'Баскетбол',
    description: 'Юношеский чемпионат',
    location: 'Спортзал №3',
    participants: 10,
  },
  {
    id: 4,
    type: 'music',
    name: 'Rock Festival',
    description: 'Фестиваль рок-групп',
    location: 'Парк культуры',
    genre: 'Rock',
  },
  {
    id: 5,
    type: 'sport',
    name: 'Волейбол',
    description: 'Соревнования среди колледжей',
    location: 'Пляжный центр',
    participants: 12,
  },
  {
    id: 6,
    type: 'music',
    name: 'Classic Evenings',
    description: 'Концерт классической музыки',
    location: 'Концертный зал “Филармония”',
    genre: 'Classical',
  },
  {
    id: 7,
    type: 'sport',
    name: 'Легкая атлетика',
    description: 'Сборная школ района',
    location: 'Стадион “Олимп”',
    participants: 30,
  },
  {
    id: 8,
    type: 'music',
    name: 'EDM Party',
    description: 'Ночная вечеринка с DJ',
    location: 'Клуб “Pulse”',
    genre: 'Electronic',
  },
  {
    id: 9,
    type: 'sport',
    name: 'Настольный теннис',
    description: 'Любительский турнир',
    location: 'ФОК “Центр”',
    participants: 4,
  },
  {
    id: 10,
    type: 'music',
    name: 'Acoustic Sunday',
    description: 'Выступления уличных музыкантов',
    location: 'Главная площадь',
    genre: 'Acoustic',
  },
];
